### PR TITLE
DM init

### PR DESCRIPTION
**Pull request by paulzierep**
This is the first data manager configuration for this tool.
It worked locally with the `test-db` (just copying the test-db data into the `GALAXY_DATA_MANAGER_DATA_PATH` dir)
and `phylodb` using the tools own DB download function.

Needs to be tested with the tool. Using something like:
```
  <param name="reference_dir" type="select" label="Select a eukulele database">
      <options from_data_table="eukulele_db_versioned">
          <validator message="No eukulele database is available" type="no_options" />
      </options>
  </param>
```

### CODE REVIEW

**Comment by paulzierep** [comment]
The fixes for `Eukulele2.xml` make the tool run (but it takes long even with the test DB - that might be since there is not CPU flag that allows to parallel the tool), some notes:
* there is no `format="directory"` - this should be handled with collections - see the new way tool input/output is defined ...

**Comment by paulzierep** [comment]
The tool does load a DB, although a local reference was given, need to check why ...?

**Comment by paulzierep** [comment]
> The tool does load a DB, although a local reference was given, need to check why ...?

This works:

```
EUKulele -s MAGs_input -o output -m mets --ref_fasta test_db/reference.pep.fa --tax_table test_db/tax-table.txt --protein_map test_db/protein-map.json --alignment_choice diamond --n_ext fasta --consensus_cutoff 0.75
```

**Comment by paulzierep** [comment]
> > The tool does load a DB, although a local reference was given, need to check why ...?
> 
> This works:
> 
> ```
> EUKulele -s MAGs_input -o output -m mets --ref_fasta test_db/reference.pep.fa --tax_table test_db/tax-table.txt --protein_map test_db/protein-map.json --alignment_choice diamond --n_ext fasta --consensus_cutoff 0.75
> ```

It makes the tool run but the output is:
```
Setting things up...                                                                                                                                                                                        
Found database folder for . in current directory; will not re-download.                                                                                                                                     
Creating a diamond reference from database files...                                                                                                                                                         
Aligning to reference database...                                                                                                                                                                           
Aligning sample sample_8...                                                                                                                                                                                 
Aligning sample sample_4...                                                                                                                                                                                 
Aligning sample sample_0...                                                                                                                                                                                 
Aligning sample sample_2...                                                                                                                                                                                 
Aligning sample sample_1...                                                                                                                                                                                 
Aligning sample sample_9...                                                                                                                                                                                 
Aligning sample sample_7...                                                                                                                                                                                 
Aligning sample sample_3...                                                                                                                                                                                 
Diamond process exited for sample sample_8.                                                                                                                                                                 
Diamond did not complete successfully for sample sample_8 with rc code 1                                                                                                                                    
Aligning sample sample_5...                                                                                                                                                                                 
Diamond process exited for sample sample_3.                                                                                                                                                                 
Diamond process exited for sample sample_0.                                                                                                                                                                 
Diamond did not complete successfully for sample sample_3 with rc code 1                                                                                                                                    
Diamond process exited for sample sample_4.                                                                                                                                                                 
Diamond did not complete successfully for sample sample_0 with rc code 1                                                                                                                                    
Diamond process exited for sample sample_9.                                                                                                                                                                 
Diamond process exited for sample sample_2.                                                                                                                                                                 
Diamond process exited for sample sample_1.                                                                                                                                                                 
Aligning sample sample_6...                                                                                                                                                                                 
Diamond did not complete successfully for sample sample_1 with rc code 1
Diamond did not complete successfully for sample sample_9 with rc code 1
Diamond did not complete successfully for sample sample_4 with rc code 1
Diamond did not complete successfully for sample sample_2 with rc code 1
Diamond process exited for sample sample_7.
Diamond did not complete successfully for sample sample_7 with rc code 1
Diamond process exited for sample sample_5.
Diamond did not complete successfully for sample sample_5 with rc code 1
Diamond process exited for sample sample_6.
Diamond did not complete successfully for sample sample_6 with rc code 1
Alignment did not complete successfully.
```
It seems there is something off when running diamond.
Did it work for you locally?

**Comment by paulzierep** [comment]
wohoo, I think I found the issue, seems like the absolute path needs to be set to  `--ref_fasta`

This works:

```
EUKulele -s MAGs_input -o output -m mags --ref_fasta /home/paul/git/people/mina/EUKulele/test-data/test_db/reference-pep-trunc.pep.faa --tax_table test_db/tax-table.txt --protein_map test_db/protein-map.json --alignment_choice diamond --n_ext .faa  --consensus_cutoff 0.75
```

**Comment by paulzierep** [comment]
But it opens windows and it stuck until they are closed, so a fix for the tool is needed: https://github.com/AlexanderLabWHOI/EUKulele/issues/64 
It is actually easy, do you want to make a PR for the tool ?

**Review by Minamehr — APPROVED** [review]

**Review by Minamehr — APPROVED** [review]

**Pull request merged**
